services:
  uraniarr:
    container_name: uraniarr
    build: .
    image: uraniarr
    ports:
      - "8000:8000"
    environment:
      - CONFIG_DIR=/config
    volumes:
      - <dev>:/config
      - <dev>:/data
    
