services:
  lesarr:
    container_name: lesarr
    build: .
    image: lesarr
    ports:
      - "8000:8000"
    environment:
      - CONFIG_DIR=/config
    volumes:
      - C:\Users\janni\Documents\private-git\Lesarr\config:/config
      - C:\Users\janni\Downloads\sab:/data
    